INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    1,
    '갤럭시 S24',
    'Samsung',
    'Galaxy S24',
    1150000,
    30,
    'Snapdragon 8 Gen 3',
    '8GB',
    '256GB',
    '6.2인치',
    'Android',
    '블랙',
    '고성능 안드로이드 스마트폰',
    'galaxy-s24.jpg',
    '/images/products/galaxy-s24.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    1,
    '아이폰 15',
    'Apple',
    'iPhone 15',
    1250000,
    25,
    'A16 Bionic',
    '6GB',
    '128GB',
    '6.1인치',
    'iOS',
    '블루',
    '일상 사용에 적합한 iOS 스마트폰',
    'iphone-15.jpg',
    '/images/products/iphone-15.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    2,
    'LG 그램 16',
    'LG',
    'Gram 16',
    1890000,
    15,
    'Intel Core Ultra 7',
    '16GB',
    '512GB SSD',
    '16인치',
    'Windows 11',
    '화이트',
    '가볍고 휴대성이 좋은 노트북',
    'lg-gram-16.jpg',
    '/images/products/lg-gram-16.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    2,
    '맥북 에어 13',
    'Apple',
    'MacBook Air 13',
    1590000,
    12,
    'Apple M3',
    '8GB',
    '256GB SSD',
    '13.6인치',
    'macOS',
    '실버',
    '휴대성과 성능을 모두 갖춘 노트북',
    'macbook-air-13.jpg',
    '/images/products/macbook-air-13.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    3,
    '아이패드 에어',
    'Apple',
    'iPad Air',
    899000,
    20,
    'Apple M2',
    '8GB',
    '128GB',
    '11인치',
    'iPadOS',
    '스페이스 그레이',
    '학습과 작업에 적합한 태블릿',
    'ipad-air.jpg',
    '/images/products/ipad-air.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    3,
    '갤럭시 탭 S9',
    'Samsung',
    'Galaxy Tab S9',
    998000,
    18,
    'Snapdragon 8 Gen 2',
    '8GB',
    '256GB',
    '11인치',
    'Android',
    '그라파이트',
    '영상 감상과 필기에 적합한 태블릿',
    'galaxy-tab-s9.jpg',
    '/images/products/galaxy-tab-s9.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    4,
    '무선 블루투스 마우스',
    'Logitech',
    'M350',
    35000,
    100,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '블랙',
    '휴대성이 좋은 무선 블루투스 마우스',
    'mouse-m350.jpg',
    '/images/products/mouse-m350.jpg',
    'SALE'
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status
) VALUES (
    seq_product.NEXTVAL,
    4,
    '기계식 키보드',
    'Keychron',
    'K2',
    129000,
    40,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '그레이',
    '타건감이 좋은 무선 기계식 키보드',
    'keychron-k2.jpg',
    '/images/products/keychron-k2.jpg',
    'SALE'
);

COMMIT;