CREATE SEQUENCE seq_member
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_category
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_product
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_cart_item
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_orders
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_order_item
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_board
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE seq_board_comment
    START WITH 1
    INCREMENT BY 1
    NOCACHE;