INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    1,
    '갤럭시 S24',
    'Samsung',
    'Galaxy S24',
    1150000,
    30,
    'Snapdragon 8 Gen 3',
    '8GB',
    '256GB',
    '6.2인치',
    'Android',
    '블랙',
    '고성능 안드로이드 스마트폰',
    '갤럭시24.jpeg',
    '/uploads/갤럭시24.jpeg',
    'SALE',
    12,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    1,
    '아이폰 15',
    'Apple',
    'iPhone 15',
    1250000,
    25,
    'A16 Bionic',
    '6GB',
    '128GB',
    '6.1인치',
    'iOS',
    '블루',
    '일상 사용에 적합한 iOS 스마트폰',
    '아이폰15.jpg',
    '/uploads/아이폰15.jpg',
    'SALE',
    18,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    1,
    '아이폰 15 프로',
    'Apple',
    'iPhone 15 Pro',
    1550000,
    16,
    'A17 Pro',
    '8GB',
    '256GB',
    '6.1인치',
    'iOS',
    '내추럴 티타늄',
    '고성능 카메라와 칩셋을 탑재한 프리미엄 스마트폰',
    '아이폰 15 프로.jpg',
    '/uploads/아이폰 15 프로.jpg',
    'SALE',
    9,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    1,
    '픽셀 8',
    'Google',
    'Pixel 8',
    980000,
    28,
    'Google Tensor G3',
    '8GB',
    '128GB',
    '6.2인치',
    'Android',
    '그레이',
    '깔끔한 안드로이드 경험과 카메라 성능이 좋은 스마트폰',
    '픽셀 8.jpeg',
    '/uploads/픽셀 8.jpeg',
    'SALE',
    7,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    1,
    '갤럭시 Z 플립5',
    'Samsung',
    'Galaxy Z Flip5',
    1390000,
    22,
    'Snapdragon 8 Gen 2',
    '8GB',
    '256GB',
    '6.7인치',
    'Android',
    '민트',
    '접어서 휴대하기 좋은 폴더블 스마트폰',
    '갤럭시 Z 플립5.png',
    '/uploads/갤럭시 Z 플립5.png',
    'SALE',
    5,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    2,
    'LG 그램 16',
    'LG',
    'Gram 16',
    1890000,
    15,
    'Intel Core Ultra 7',
    '16GB',
    '512GB SSD',
    '16인치',
    'Windows 11',
    '화이트',
    '가볍고 휴대성이 좋은 노트북',
    'LG그램.jpeg',
    '/uploads/LG그램.jpeg',
    'SALE',
    14,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    2,
    '맥북 에어 13',
    'Apple',
    'MacBook Air 13',
    1590000,
    12,
    'Apple M3',
    '8GB',
    '256GB SSD',
    '13.6인치',
    'macOS',
    '실버',
    '휴대성과 성능을 모두 갖춘 노트북',
    '맥북에어13.jpg',
    '/uploads/맥북에어13.jpg',
    'SALE',
    20,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    2,
    '삼성 갤럭시북4 프로',
    'Samsung',
    'Galaxy Book4 Pro',
    1720000,
    14,
    'Intel Core Ultra 5',
    '16GB',
    '512GB SSD',
    '14인치',
    'Windows 11',
    '문스톤 그레이',
    '가볍고 성능 좋은 업무용 노트북',
    '삼성 갤럭시북4 프로.png',
    '/uploads/삼성 갤럭시북4 프로.png',
    'SALE',
    11,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    2,
    '레노버 아이디어패드 슬림5',
    'Lenovo',
    'IdeaPad Slim 5',
    890000,
    21,
    'AMD Ryzen 5',
    '16GB',
    '512GB SSD',
    '15.6인치',
    'Windows 11',
    '그레이',
    '가성비가 좋은 학습 및 사무용 노트북',
    '레노버 아이디어패드 슬림5.jpg',
    '/uploads/레노버 아이디어패드 슬림5.jpg',
    'SALE',
    8,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    2,
    'ASUS 비보북 15',
    'ASUS',
    'Vivobook 15',
    790000,
    19,
    'Intel Core i5',
    '16GB',
    '512GB SSD',
    '15.6인치',
    'Windows 11',
    '실버',
    '일상 작업과 온라인 강의에 적합한 노트북',
    'ASUS 비보북 15.png',
    '/uploads/ASUS 비보북 15.png',
    'SALE',
    6,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    3,
    '아이패드 에어',
    'Apple',
    'iPad Air',
    899000,
    20,
    'Apple M2',
    '8GB',
    '128GB',
    '11인치',
    'iPadOS',
    '스페이스 그레이',
    '학습과 작업에 적합한 태블릿',
    '아이패드에어.jpeg',
    '/uploads/아이패드에어.jpeg',
    'SALE',
    13,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    3,
    '갤럭시 탭 S9',
    'Samsung',
    'Galaxy Tab S9',
    998000,
    18,
    'Snapdragon 8 Gen 2',
    '8GB',
    '256GB',
    '11인치',
    'Android',
    '그라파이트',
    '영상 감상과 필기에 적합한 태블릿',
    '갤럭시탭S9.jpeg',
    '/uploads/갤럭시탭S9.jpeg',
    'SALE',
    10,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    3,
    '갤럭시 탭 A9 플러스',
    'Samsung',
    'Galaxy Tab A9 Plus',
    369000,
    45,
    'Snapdragon 695',
    '4GB',
    '64GB',
    '11인치',
    'Android',
    '실버',
    '가볍게 사용하기 좋은 보급형 태블릿',
    '갤럭시 탭 A9 플러스.jpeg',
    '/uploads/갤럭시 탭 A9 플러스.jpeg',
    'SALE',
    4,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    3,
    '레노버 탭 P12',
    'Lenovo',
    'Tab P12',
    459000,
    33,
    'MediaTek Dimensity 7050',
    '8GB',
    '128GB',
    '12.7인치',
    'Android',
    '스톰 그레이',
    '큰 화면으로 영상 시청과 필기에 적합한 태블릿',
    '레노버 탭 P12.jpeg',
    '/uploads/레노버 탭 P12.jpeg',
    'SALE',
    6,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    3,
    '서피스 프로 9',
    'Microsoft',
    'Surface Pro 9',
    1380000,
    11,
    'Intel Core i5',
    '8GB',
    '256GB SSD',
    '13인치',
    'Windows 11',
    '플래티넘',
    '태블릿과 노트북처럼 사용할 수 있는 2-in-1 기기',
    '서피스 프로 9.jpeg',
    '/uploads/서피스 프로 9.jpeg',
    'SALE',
    3,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    4,
    '무선 블루투스 마우스',
    'Logitech',
    'M350',
    35000,
    100,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '블랙',
    '휴대성이 좋은 무선 블루투스 마우스',
    '로지텍무선블루투스마우스.jpg',
    '/uploads/로지텍무선블루투스마우스.jpg',
    'SALE',
    25,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    4,
    '기계식 키보드',
    'Keychron',
    'K2',
    129000,
    40,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '그레이',
    '타건감이 좋은 무선 기계식 키보드',
    '기계식키보드.jpeg',
    '/uploads/기계식키보드.jpeg',
    'SALE',
    17,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    4,
    '노트북 거치대',
    'MOFT',
    'Laptop Stand',
    42000,
    90,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '블랙',
    '책상 위에서 노트북 각도를 조절하기 좋은 거치대',
    '노트북거치대.jpg',
    '/uploads/노트북거치대.jpg',
    'SALE',
    19,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    4,
    'USB-C 멀티 허브',
    'Anker',
    'PowerExpand 7-in-1',
    69000,
    80,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '실버',
    '노트북과 태블릿에 연결하기 좋은 USB-C 멀티 허브',
    'USB-C 멀티 허브.jpeg',
    '/uploads/USB-C 멀티 허브.jpeg',
    'SALE',
    15,
    SYSDATE
);

INSERT INTO product (
    product_id,
    category_id,
    product_name,
    brand,
    model_name,
    price,
    stock,
    cpu,
    ram,
    storage_capacity,
    screen_size,
    os,
    color,
    description,
    image_name,
    image_path,
    status,
    sales_count,
    created_at
) VALUES (
    seq_product.NEXTVAL,
    4,
    '무선 이어폰',
    'Samsung',
    'Galaxy Buds',
    119000,
    70,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '화이트',
    '가볍고 착용감이 좋은 무선 이어폰',
    '갤럭시버즈4.jpg',
    '/uploads/갤럭시버즈4.jpg',
    'SALE',
    21,
    SYSDATE
);

COMMIT;