DROP TABLE board_comment CASCADE CONSTRAINTS PURGE;
DROP TABLE board CASCADE CONSTRAINTS PURGE;

DROP TABLE order_item CASCADE CONSTRAINTS PURGE;
DROP TABLE orders CASCADE CONSTRAINTS PURGE;

DROP TABLE cart_item CASCADE CONSTRAINTS PURGE;
DROP TABLE product CASCADE CONSTRAINTS PURGE;
DROP TABLE category CASCADE CONSTRAINTS PURGE;
DROP TABLE shop_member CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE seq_member;
DROP SEQUENCE seq_category;
DROP SEQUENCE seq_product;
DROP SEQUENCE seq_cart_item;
DROP SEQUENCE seq_orders;
DROP SEQUENCE seq_order_item;
DROP SEQUENCE seq_board;
DROP SEQUENCE seq_board_comment;